### ISSUE TITLE
Как завершить сессию

### ISSUE THREAD

**Issue by Ducalius** [nm17/netschoolapi#1]
В системе отображаются все начатые сессии

**Comment by nm17** [comment]
Забыл добавить, сейчас попробую сделать.

**Comment by nm17** [comment]
@Ducalius выложил версию 1.2.0: https://pypi.org/project/netschoolapi/1.2.0/

Напиши заработала ли `logout()` функция или нет.

**Comment by Ducalius** [comment]
> @Ducalius выложил версию 1.2.0: https://pypi.org/project/netschoolapi/1.2.0/
> 
> Напиши заработала ли `logout()` функция или нет.

Спасибо, все работает
