### ISSUE TITLE
Получение отчета

### ISSUE THREAD

**Issue by BTCable** [nm17/netschoolapi#21]
Привет, заинтересовал твой проект. Короче говоря, нужно каким то образом вытаскивать pdfку с отчетами, возможно такое реализовать?

**Comment by nm17** [comment]
Надо будет сделать. Пока что закрую эту issue т.к это дубликат #18

**Comment by igorlanov** [comment]
Пока что разбираемся с этим. Оказалось, что это сложнее, чем ожидалось
