### ISSUE TITLE
Неактуальная версия в менеджере пакетов

### ISSUE THREAD

**Issue by RobotoLev** [nm17/netschoolapi#36]
#### Описание проблемы

В pip висит неактуальная версия 5.0.1 (в репозитории 5.0.2)

#### Шаги, чтобы воспроизвести проблему

  1. Залить актуальную версию библиотеки в PyPI

#### Каков ожидаемый результат?

  - Версия 5.0.2, которую можно нормально установить

**Comment by nm17** [comment]
Исправил @RobotoLev
